### ISSUE TITLE
WingStyle folder is a link

### ISSUE THREAD

**Issue by bwoebi** [IngwiePhoenix/drag0n#2]
https://github.com/IngwiePhoenix/drag0n/commit/4d488da2dc6ae011bfee6dc3006664d625a957a2

You added WingStyle as a link to your local WingStyle clone. I'd consider to change it to a github _link_.

**Comment by IngwiePhoenix** [comment]
I am trying to, but not succeeding x)
Currently I also tried uploading a very recent built with WingStyle's project folder right inside drag0n, but now github for mac says "You dont have permission"... I am trying to get this fixed.
Am 05.09.2013 um 01:21 schrieb Bob Weinand notifications@github.com:

**Comment by IngwiePhoenix** [comment]
I finally managed to git-link it, i belive. Please let me know if it worked.

**Comment by bwoebi** [comment]
Still not correct. You seem to have it defined in a ssh way. Please use the git:// or the https:// way. Else I won't be able to fetch it (over the normal way).

_So einfach ist das nicht :P_

**Comment by IngwiePhoenix** [comment]
Recent commit includes the HTTPS link instead.
...Dont tell me youre german, i'd freak out; because I am from Germany :)
Am 05.09.2013 um 21:59 schrieb Bob Weinand notifications@github.com:

**Comment by bwoebi** [comment]
Dass du Deutscher bist sieht man ja schon an deiner Benutzerseite.

Und nö, … Deutscher bin ich nicht; Luxemburger aber ;-)

**Comment by IngwiePhoenix** [comment]
Trozdem sehr cool. :)
Sag bescheid ob die .gitmodule richtig geupdatet wurden ^^

Am 05.09.2013 um 22:17 schrieb Bob Weinand notifications@github.com:

**Comment by bwoebi** [comment]
Perfekt, funktionniert. Jetzt noch meinen Patch mergen... ;-)

**Comment by bwoebi** [comment]
Doch nicht…

```
sh-3.2# git submodule init
Submodule 'drag0n.app/Contents/Library/WingStyle' (https://github.com/IngwiePhoenix/drag0n.git) registered for path 'drag0n.app/Contents/Library/WingStyle'
sh-3.2# git submodule update
Cloning into 'drag0n.app/Contents/Library/WingStyle'...
remote: Counting objects: 4554, done.
remote: Compressing objects: 100% (2863/2863), done.
remote: Total 4554 (delta 1457), reused 4526 (delta 1435)
Receiving objects: 100% (4554/4554), 102.43 MiB | 5.14 MiB/s, done.
Resolving deltas: 100% (1457/1457), done.
fatal: reference is not a tree: d393aa9657b42e503bcf6be889f651a625fce545
Unable to checkout 'd393aa9657b42e503bcf6be889f651a625fce545' in submodule path 'drag0n.app/Contents/Library/WingStyle'
```

**Comment by IngwiePhoenix** [comment]
Strange... o-o Bin leider kein Git-experte. Ich gug mal was man da machen kann.
Am 05.09.2013 um 22:38 schrieb Bob Weinand notifications@github.com:

**Comment by IngwiePhoenix** [comment]
Der Link war falsch! xD
Hab's geändert - jetzt sollte es stimmen.
Am 05.09.2013 um 22:41 schrieb Bob Weinand notifications@github.com:

**Comment by bwoebi** [comment]
```
git clone --recursive https://github.com/bwoebi/drag0n.git
Cloning into 'drag0n'...
remote: Counting objects: 4563, done.
remote: Compressing objects: 100% (2870/2870), done.
remote: Total 4563 (delta 1461), reused 4533 (delta 1437)
Receiving objects: 100% (4563/4563), 102.43 MiB | 5.07 MiB/s, done.
Resolving deltas: 100% (1461/1461), done.
Checking out files: 100% (4512/4512), done.
Submodule 'drag0n.app/Contents/Library/WingStyle' (https://github.com/IngwiePhoenix/WingStyle.git) registered for path 'drag0n.app/Contents/Library/WingStyle'
Cloning into 'drag0n.app/Contents/Library/WingStyle'...
remote: Counting objects: 248, done.
remote: Compressing objects: 100% (182/182), done.
remote: Total 248 (delta 140), reused 164 (delta 59)
Receiving objects: 100% (248/248), 38.98 KiB, done.
Resolving deltas: 100% (140/140), done.
Submodule path 'drag0n.app/Contents/Library/WingStyle': checked out 'd393aa9657b42e503bcf6be889f651a625fce545'
```

… perfekt! :+1:
