### ISSUE TITLE
Wrong URL paths

### ISSUE THREAD

**Issue by bwoebi** [IngwiePhoenix/drag0n#3]
The URL paths are wrong: they're absolute to / while the application tries to resolve them relative to the Contents folder. Please change the URLs to be relative to `drag0n.app/Contents`.

I get errors that it tries to open the file:

```
/Applications/drag0n/drag0n.app/Contents/Applications/drag0n/drag0n.app/Contents/MacOS/d0GUI.php
```

Called URL is:

```
http://appjs/Applications/drag0n/drag0n.app/Contents/MacOS/d0GUI.php?...some params...
```

instead of:

```
http://appjs/MacOS/d0GUI.php?...some params...
```

**Comment by IngwiePhoenix** [comment]
I have found a fix for that a while ago, its just, I havent uploaded anything in a while ^^;
I had the issue too. I figured the fix by changing a value in Yii from the Controller.php file.
I am going to upload the fix today.
Am 05.09.2013 um 01:43 schrieb Bob Weinand notifications@github.com:

**Comment by IngwiePhoenix** [comment]
The new fix is now up. Tested it on my second mashine and it worked very fine. Try it out :3

**Comment by bwoebi** [comment]
Ja, funktionniert inzwischen :-)
