### ISSUE TITLE
Fullscreen aus?

### ISSUE THREAD

**Issue by bwoebi** [IngwiePhoenix/drag0n#4]
Fullscreen ist bei der aktuellen App echt suboptimal, je nach Auflösung. Magst du das bitte ändern?

Dazu müsste jetzt nur die MacOS/d0GUI.js geändert werden:

Folgendes entfernen:

```
   // force fullscreen
   this.frame.fullscreen();
```

und

```
  width : 1024,
  height : 768,
  top: -1,
  left: -1,
```

ändern zu:

```
  width : 1024,
  height : 768,
  top: 768,
  left: 1024,
```

**Comment by IngwiePhoenix** [comment]
Habe bis jetzt stets auf 13" und 11" getestet wie es aussieht. Aber ich kann es gern deaktivieren. Ich fand nur es passte besser zum Design ^^; Kommt gleich als commit.
Am 05.09.2013 um 23:32 schrieb Bob Weinand notifications@github.com:

**Comment by bwoebi** [comment]
Naja, ich habe hier einen 15" native resolution retina MBP (also 2880x1800) und einen 27" iMac (2560x1440)

Da sieht sowas komplett verzerrt aus ;-)

**Comment by bwoebi** [comment]
Aber funktionniert bestens, dankeschön :-)

**Comment by IngwiePhoenix** [comment]
Ohhh.... ^^. Naja, auf nem Retina konnte ich das noch nicht testen. Aber gut zu wissen das es JETZT getestet wird! :D
Viel spaß beim rum-poken :p
Am 05.09.2013 um 23:46 schrieb Bob Weinand notifications@github.com:

**Comment by bwoebi** [comment]
Wie meinst du "rum-poken"?

Und naja… es brauch jetzt noch mehr Inhalt als nur eine Hassnachricht gegen Perl^^ (mag ich auch nicht)

**Comment by IngwiePhoenix** [comment]
Is ja auch nur ein Alpha-Preview.
Ich werd erstmal das ganze multithreading und YAML in den core integireren müssen - sprich in drag0n.app/Contents/Application/comonents/d0.php
Mit "rum-poken" mein ich, "rumprobieren" ^^;
Am 05.09.2013 um 23:55 schrieb Bob Weinand notifications@github.com:

**Comment by bwoebi** [comment]
wozu zur Hölle brauchst du hier YAML?!?

json ist auch ganz nett…

Und sowieso… ein Yii Framework braucht auch keiner… Vor allem schon weil es ein Framework ist^^ (vanilla PHP (mit exts) ist eh das beste Framework)

**Comment by IngwiePhoenix** [comment]
JSON verpasst mir hin und wieder nen netten Augenkrebs x). YAML kann man wehnigstens auch mal lesen o.o
Das Yii benutze ich momentan um mir einfach ne flotte OOP-Basis zu schaffen. Wenn sich drag0n weiter entwickelt, werd ich vielleicht auch eher ein "eigenes Framework" erstellen. Aber ich bin mit Yii super zufrieden und gut bedient. ^^
Dazu kommt das ich keine exts schreiben kann ;)
Am 06.09.2013 um 00:04 schrieb Bob Weinand notifications@github.com:

**Comment by bwoebi** [comment]
Solange man kein Einzeiler JSON hat und brav JSON nach einem sauberen Stil schreibt, alles kein Problem… Oder ist https://de.wikipedia.org/wiki/JavaScript_Object_Notation#Beispiel bspw. augenkrebserregend?

Btw derzeit sind reine PHP arrays auch leserlich mit der short array syntax.

mit exts meinte ich jetzt eher pcntl, pthreads usw. keine eigenen.

**Comment by IngwiePhoenix** [comment]
Die JavaScript notation kann ich schon lesen. Ich hab nur mit meiner Sehbehinderung - ich bin auf einem Auge blind und auf dem anderen seh ich nur ein bisschen - ab und zu mal ein Orientierungsverlust und bekomme gewaltige Kopfschmerzen. Bei YAML gibts nich zu viel zeug mit Anführungsstrichen oder Kommas.

Die Short-Syntax find ich ja eh schon hammer - deswegen wollte ich ja umbedingt auch ein möglichst hohes PHP einbinden :).

Gute exts kenn ich - auser pthreads - leider keine.
Am 06.09.2013 um 00:20 schrieb Bob Weinand notifications@github.com:

**Comment by bwoebi** [comment]
exts habe ich übrigens runkit, pecl_http und pthreads installiert.

YAML finde ich ja schon fast zu viel des Guten eigentlich. Man kann auch gleich 96 Frameworks und Bibliotheken installieren; aber dann wird der Code alles, nur nicht übersichtlich.

Btw. bei OS X (10.8) ist noch php 5.3 vorinstalliert… Würde mal warten bis Mavericks released ist (aber da es eh nur eine Alpha bleibt bis nach dem Release, egal^^)

**Comment by IngwiePhoenix** [comment]
Ah, runkit...da hab ich auch schon mit dem Gedanken gespielt es einzubinden. Eventuell. Aber bin mir nicht sicher.

Naja - so viel ist in drag0n jetzt auch nicht drinn. Ein framework (`Yii`), eine Bibliothek (`WingStyle`) und ein paar kleine Helferklassen (`Apple`, `Spyc`, `PHPLinq`, welches ich noch am Testen bin)..sollte eigendlich noch im Bereich der Grenzen liegen

Naja fürs Erste werd ich YAML benutzen damit ich mich grad so derp damit beschäftigt hab :p

Ich versuche, OS unabhängig zu sein. Zudem bezweifel ich das Mavericks eine PHP 5.5 version mitbringt :p Daher bleib ich bei meiner selbst-enthaltenen Variante. ^^
Am 06.09.2013 um 00:38 schrieb Bob Weinand notifications@github.com:

**Comment by bwoebi** [comment]
Jo, inzwischen hast du auch alle libs und so eingebunden…

Ich dachte eigentlich an PHP 5.4 bzgl. Mavericks. (Reicht ja eig.^^) Aber die eigene Variante ist immer gut ;-)

Wozu braucht man denn eigentlich PHPLinq?

**Comment by IngwiePhoenix** [comment]
Mit PHPLinq möchte ich mir schon fast unnötige foreaches und sowas spaaren um schnell Pakete oder Resourcen zu filtern/suchen. Ich bins noch am testen, ob es auch das tut was und wie ich es will. ^^;
Am 06.09.2013 um 17:52 schrieb Bob Weinand notifications@github.com:

**Comment by bwoebi** [comment]
Okay… mal sehen. Immer schön updaten… bin gespannt auf die nächsten Fortschritte hier :-)

**Comment by IngwiePhoenix** [comment]
Yup :) Updates werden weiter rollen ^^
Am 06.09.2013 um 20:53 schrieb Bob Weinand notifications@github.com:
